{% set name = "unstructured-client" %}
{% set version = "0.25.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unstructured-client-{{ version }}.tar.gz
  sha256: fcc461623f58fefb0e22508e28bf653a8f6934b9779cb4a90dd68d77a39fb5b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - cryptography >=3.1
    - httpx >=0.27.0
    - nest-asyncio >=1.6.0
    - requests-toolbelt >=1.0.0
    - python >=3.8
    - certifi >=2023.7.22
    - charset-normalizer >=3.2.0
    - dataclasses-json >=0.6.4
    - deepdiff >=6.0
    - idna >=3.4
    - jsonpath-python >=1.0.6
    - marshmallow >=3.19.0
    - mypy_extensions >=1.0.0
    - packaging >=23.1
    - pypdf >=4.0
    - python-dateutil >=2.8.2
    - requests >=2.31.0
    - six >=1.16.0
    - typing_inspect >=0.9.0
    - typing-extensions >=4.7.1
    - urllib3 >=1.26.18

test:
  imports:
    - unstructured_client
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python Client SDK for Unstructured API
  home: https://github.com/Unstructured-IO/unstructured-python-client
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
