{% set name = "unstructured-client" %}
{% set version = "0.26.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 02f7183ab16db6ec48ad1ac75c01b05967c87c561a89e96d9ffb836baed902d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - eval-type-backport >=0.2.0,<0.3.0
    - pydantic >=2.9.0,<2.10.0
    - cryptography >=3.1
    - httpx >=0.27.0
    - nest-asyncio >=1.6.0
    - requests-toolbelt >=1.0.0
    - python >=3.8
    - certifi >=2023.7.22
    - charset-normalizer >=3.2.0
    - dataclasses-json >=0.6.4
    - deepdiff >=6.0
    - idna >=3.4
    - jsonpath-python >=1.0.6,<2.0.0
    - marshmallow >=3.19.0
    - mypy_extensions >=1.0.0
    - packaging >=23.1
    - pypdf >=4.0
    - python-dateutil 2.8.2
    - requests >=2.31.0
    - six >=1.16.0
    - typing_inspect >=0.9.0,<0.10.0
    - typing-extensions >=4.7.1
    - urllib3 >=1.26.18

test:
  imports:
    - unstructured_client
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python Client SDK for Unstructured API
  home: https://github.com/Unstructured-IO/unstructured-python-client
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
